version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mh$xN89?6n32$=:b1Fx&+9!<sfA|H
    ports:
      - 27017:27017
    volumes:
      - dbdata7:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mh$xN89?6n32$=:b1Fx&+9!<sfA|H
      ME_CONFIG_MONGODB_URL: mongodb://root:mh$xN89?6n32$=:b1Fx&+9!<sfA|H@mongo/
      ME_CONFIG_BASICAUTH_USERNAME: flabby
      ME_CONFIG_BASICAUTH_PASSWORD: m%KC=P03#8{W

volumes:
  dbdata7: